name: System32
version: 1.002
description: The must have essential for every server!
main: me.kyllian.system32.System32Plugin
softdepend: [PlaceholderAPI]

commands:
  group:
    usage: /<command>
    description: Default
  player:
    usage: /<command>
    description: Default
  spawn:
    usage: /<command>
    description: Default
  setspawn:
    usage: /<command>
    description: Default
  delspawn:
    usage: /<command>
    description: Default
    aliases: [removespawn, remspawn, deletespawn]